blank_issues_enabled: true
contact_links:
  - name: Support/Discussions
    url: https://discord.gg/J3UWtzWSkT
    about: Please join our discord server if you wish to submit suggestions, seek support, or discuss all things Orchestrator.
