name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:

  file_changes:
    name: "Detect changes"
    runs-on: ubuntu-latest
    outputs:
      documentation-changed: ${{ steps.changed-files-documentation.outputs.any_changed }}
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get modified files (documentation)
        id: changed-files-documentation
        uses: tj-actions/changed-files@v42.0.5
        with:
          files: |
            docs/**

  deploy:
    name: "Deploy documentation changes"
    needs: [ file_changes ]
    runs-on: ubuntu-latest
    # if: ${{ needs.file_changes.outputs.documentation-changed == 'true' }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Checkout Action (UI)
        uses: actions/checkout@v4
        with:
          repository: Vahera/vahera-docs-ui
          path: ui

      - name: Build UI
        run: |
          npm install -g gulp-cli
          npm install
          npm install -g @antora/cli@3.1 @antora/site-generator@3.1
          gulp build
          gulp bundle:pack
        working-directory: ./ui

      - name: Checkout Action (UI Builder)
        uses: actions/checkout@v4
        with:
          repository: Vahera/vahera-docs-builder
          path: builder

      - name: Build documentation
        working-directory: ./builder
        run: |
          cp ../ui/build/ui-bundle.zip ./ui-bundle.zip 
          antora playbook.yml 

#      - name: Sync Documentation
#        uses: burnett01/rsync-deployments@6.0.0
#        with:
#          switches: -avh --recursive
#          path: ./builder/build
#          remote_path: ${{ secrets.SSH_DOCS_PATH }}
#          remote_host: ${{ secrets.SSH_DOCS_HOST }}
#          remote_user: ${{ secrets.SSH_DOCS_USER }}
#          remote_key: ${{ secrets.SSH_DOCS_PRIVATE_KEY }}
